# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [--config=setup.cfg]
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [-sp=setup.cfg]
